---
- name: DBserver setup
  hosts: asb-node02
  become: yes
  tasks:
    - name: Install mariadb
      yum:
        name: mariadb-server
        state: present

    - name: Install pymysql
      yum:
        name: python3-PyMySQL
        state: present

    - name: Start & enable service mariadb
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Create a new database with name "accounts"
      community.mysql.mysql_db:
        name: accounts
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock

    - name: Create database user with name 'vprofile' and password 'admin123' with all database privileges
      community.mysql.mysql_user:
        name: vprofile
        password: 'admin123'
        priv: '*.*:ALL'
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock